### ISSUE TITLE
key from recovery phrase fails with "Invalid number of words"

### ISSUE THREAD

**Issue by johnmathews** [input-output-hk/cardano-addresses#107]
Using the examples in the README, I first generate a mnemonic: 
`docker run --rm cardano-address recovery-phrase generate --size 12 > phrase.prv`

From this I try to get the root key using
`docker run --rm cardano-address key from-recovery-phrase Shelley < phrase.prv > root.xsk`

but this gives an error:
`user error (Invalid number of words: 9, 12, 15, 18, 21 or 24 words are expected.)`

The number of words is correct. I've tried with words each on a new line, or space separated.

Any suggestions?

**Comment by johnmathews** [comment]
`cat phrase.prv | docker run --rm -i cardano-address key from-recovery-phrase Shelley > root.xsk` does work though.

**Comment by KtorZ** [comment]
Most command from `cardano-address` read inputs from stdin, so you need to provide the `--interactive / -i` flag when running the container :+1: 

```
 docker run --rm -i cardano-address key from-recovery-phrase Shelley < phrase.prv > root.xsk
```
