### ISSUE TITLE
Same seed but different address in AdaLite and Yoroi

### ISSUE THREAD

**Issue by caetanix** [input-output-hk/cardano-addresses#129]
Hi,

I'm using cardano-address to generate seed and public address.
I want to match the /0 address that is show on Wallets, like Adalite or Yoroi, but i cant... its possible to do this with cardano-address ?

I'm using this code...

cardano-address recovery-phrase generate --size 24 > seed.txt
cat seed.txt | cardano-address key from-recovery-phrase Shelley | cardano-address key child 1852H/1815H/0H/0/0 | cardano-address key public --with-chain-code  | cardano-address address payment --network-tag mainnet

Thanks

**Comment by paweljakubas** [comment]
Hi @caetanix , 

You created enterprise address, ie. one without stake verification key included. And probably you want base address, the address with both payment and stake verification keys included.

So in order to produce base address you should do:
```
$ cardano-address recovery-phrase generate --size 24 > seed.txt
$ cardano-address key from-recovery-phrase Shelley < seed.txt > root.xsk
$ cardano-address key child 1852H/1815H/0H/0/0 < root.xsk | cardano-address key public --with-chain-code > addr.xvk
$ cardano-address key child 1852H/1815H/0H/2/0 < root.xsk | cardano-address key public --with-chain-code > stake.xvk
$ $ cardano-address address payment --network-tag mainnet < addr.xvk > payment.addr
```

**Comment by caetanix** [comment]
hi @paweljakubas 

Its very true, that was my issue!

Thanks for all the steps, now i have the base address 👍
