### ISSUE TITLE
Error on build docker image on Windows

### ISSUE THREAD

**Issue by dario97** [input-output-hk/cardano-addresses#137]
Steps:

1. Clone the last release version of this repo.
2. `docker build -t cardano-address .`

Output:

>  => [internal] load build definition from Dockerfile                                                                                                               0.3s
 => => transferring dockerfile: 32B                                                                                                                                0.2s
 => [internal] load .dockerignore                                                                                                                                  0.2s
 => => transferring context: 35B                                                                                                                                   0.1s
 => [internal] load metadata for docker.io/frolvlad/alpine-glibc:alpine-3.11_glibc-2.30                                                                            2.5s
 => [internal] load metadata for docker.io/library/haskell:8.6.5                                                                                                   2.5s
 => [build  1/13] FROM docker.io/library/haskell:8.6.5@sha256:6ae86033bfa75027fc36a63bb69e7fa41d4e7df6ae4a78baeb77dafc94488d81                                     0.0s
 => [stage-1 1/7] FROM docker.io/frolvlad/alpine-glibc:alpine-3.11_glibc-2.30@sha256:745918f5914d71975767ba29cc250c2e74b2735b314c6dd3e9889c874528b947              0.0s
 => [internal] load build context                                                                                                                                  0.2s
 => => transferring context: 13.20kB                                                                                                                               0.1s
 => CACHED [stage-1 2/7] RUN apk add --no-cache gmp=6.1.2-r1 bash=5.0.11-r1 bash-completion=2.9-r0                                                                 0.0s
 => CACHED [build  2/13] WORKDIR /build                                                                                                                            0.0s
 => CACHED [build  3/13] RUN apt-get update && apt-get install --no-install-recommends -y   build-essential=12.3   git=1:2.11.*                                    0.0s
 => CACHED [build  4/13] RUN stack upgrade --binary-version 2.1.3                                                                                                  0.0s
 => CACHED [build  5/13] COPY stack.yaml .                                                                                                                         0.0s
 => CACHED [build  6/13] RUN mkdir -p command-line core                                                                                                            0.0s
 => CACHED [build  7/13] COPY core/package.yaml core/package.yaml                                                                                                  0.0s
 => CACHED [build  8/13] COPY command-line/package.yaml command-line/package.yaml                                                                                  0.0s
 => ERROR [build  9/13] RUN stack setup                                                                                                                            7.3s
------
 > [build  9/13] RUN stack setup:
#16 7.132 Specified source-dir "lib" does not exist
#16 7.132 Specified source-dir "test" does not exist
#16 7.138 Specified file "./schemas/address-inspect.json" for extra-source-files does not exist
#16 7.138 Specified source-dir "exe" does not exist
#16 7.138 Specified source-dir "lib" does not exist
#16 7.138 Specified source-dir "test" does not exist
#16 7.139 /build/jsbits/: getDirectoryContents:openDirStream: does not exist (No such file or directory)
------
executor failed running [/bin/sh -c stack setup]: exit code: 1

**Comment by CardanoItaly** [comment]
I have the same error on Debian. Did you solve it?

**Comment by dario97** [comment]
@CardanoItaly nop, I didn't

**Comment by flynnhou** [comment]
I followed what @Polsaker committed as a quick fix for now. It works! Thanks a lot!
