### ISSUE TITLE
Create Shelley impl of Hard/SoftDerivation and GenMasterKey

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-addresses#16]
# Context

We adding support for Shelley addresses in order to work with Shelley-era nodes as implemented in cardano-node

# Decision

We are after `GenMasterKey` and `HardDerivation` / `SoftDerivation` implementations

# Acceptance Criteria

1. `GenMasterKey` interface implemented.
2. `(Hard/Soft)Derivation` interface implemented.
3. Illustrative unit tests are added

---

# Development 

# QA 

The implementation is added in `src/Cardano/Address/Style/Shelley.hs` along with extensive comments. The respective tests are added in `test/Cardano/Address/ShelleySpec.hs`

**Comment by piotr-iohk** [comment]
lgtm.

Question: is ADP-158 only to be implemented in cardano-addresses? (asking as there's no related prs on `cardano-wallet` and `cardano-wallet` does not use `cardano-addresses` atm)

cc: @paweljakubas, @KtorZ

**Comment by paweljakubas** [comment]
After we have it here in `cardano-addresses` we are going to use this library inside `cardano-wallet` and use mnemonics and address derivation
