### ISSUE TITLE
Recommended approach to use in Haskell project

### ISSUE THREAD

**Issue by b00kdev** [input-output-hk/cardano-addresses#176]
# Context

I am wanting to use the functions/data types in the `core` folder of this project in a Haskell project I am working on. Since this package isn't on hackage or stackage, what is the recommended approach? What I've seen from the other IOHK projects is to use haskell.nix, then copy/paste all the project dependencies from `cabal.project` into my `cabal.project` and go from there. Is that the correct approach or is there another recommendation?

# Decision

N/A

# Acceptance Criteria

1. A recommended approach is given?

---

# Development 

# QA

**Comment by paweljakubas** [comment]
you can add to your cabal.project something like this :

**Comment by paweljakubas** [comment]
if you want to include only `core` omit `command-line` in `subdir`
