### ISSUE TITLE
Add PaymentAddress implementation for Shelley

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-addresses#19]
# Context

We adding support for Shelley addresses in order to work with Shelley-era nodes as implemented in cardano-node

# Decision

We are after `PaymentAddress` implementation for Shelley. In Shelley, addresses will have a new format. There exist 9 types of addresses described in the following document https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl .We are currently looking to support all of them (as in, being able to recognize all of them), but the wallet and libraries will only make active use of the base address type 0, containing a public spending key hash and a public delegation key hash.
Later, the wallet and libraries will implement support for type 4, pointer addresses.The below is also the reference:
https://github.com/input-output-hk/cardano-ledger-specs/compare/cddl_address_notes#diff-d7073d7dcbeeb9e050157bf7f76d541bR73

# Acceptance Criteria

1. `PaymentAddress` interface should be implemented
2. Golden tests and properties should be added to unit tests suite

---

# Development 

# QA 

a number of things were added : 
1. Shelley impl of current interfaces
2. DelegationAddress and NetworkDescriminant interface and impls (also for Shelley)
3. Tests were added in ShelleySpec and also AddressSpec nad Test.Arbitratry were extended
4. Also numerous comments were added.

**Comment by piotr-iohk** [comment]
LGTM.
