### ISSUE TITLE
Add pointer addresses

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-addresses#30]
# Context

We are interested in base, enterprise and pointer address support for shelley at this moment

# Decision

We add pointer address support for shelley

# Acceptance Criteria

1. `PointerAddress` interface is added
2. `PointerAddress` impl for Shelley style is added.
3. Golden tests based on cardano-ledger-spec are added for base,enterprise and pointer address

---

# Development 

# QA 

1. I added `PointerAddresses` interface and Shelley impl, along with tests.
2. I added golden tests for base, enterprise and pointer addresses based on https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Address.hs#L101-L129

**Comment by piotr-iohk** [comment]
LGTM.

@paweljakubas should this be used in `cardano-wallet`? https://github.com/input-output-hk/cardano-wallet/blob/master/stack.yaml#L43 - currenlty points to revision before pointer addresses. (https://github.com/input-output-hk/cardano-addresses/commit/07280d380f3ccedba91f1ba5bc8fbd9dc83b967f)

**Comment by paweljakubas** [comment]
yes, it is going to be directly used in cardano-wallet. and when so, the commit pointing in cardano-wallet will be bumped!

**Comment by piotr-iohk** [comment]
@paweljakubas makes sense perhaps to bump it now as part of this task? My reasoning is that the sooner to integrate the better in terms of discovering potenital problems...

**Comment by paweljakubas** [comment]
now we do not use pointer addresses in cardano-wallet. I propose to bump it in cardano-wallet when we start to use it soon

**Comment by piotr-iohk** [comment]
Understood. Closing then.
