### ISSUE TITLE
Release binary for Linux etc.

### ISSUE THREAD

**Issue by melmccann** [input-output-hk/cardano-addresses#34]
Can we provide a release binary under Github releases for the CLI?

**Comment by KtorZ** [comment]
@melmccann 

The CI will now automatically create release artifacts upon releases. It is also possible to grab intermediate artifacts in-between releases from each "Continuous Integration" job: https://github.com/input-output-hk/cardano-addresses/actions/runs/140666173

see `ubuntu-latest-exe`

**Comment by melmccann** [comment]
Thank you @KtorZ
