### ISSUE TITLE
cardano-address.exe --help fails on windows

### ISSUE THREAD

**Issue by rvl** [input-output-hk/cardano-addresses#41]
On Windows 10 and Wine, `cardano-address --help` fails with the following error:

```
cardano-address.exe: <stdout>: hPutChar: invalid argument (invalid character)
```

![VirtualBox_Win10_09_07_2020_11_14_19](https://user-images.githubusercontent.com/1019641/86985901-ae055000-c1d5-11ea-8a89-9c8db3dcf2ed.png)

**Comment by KtorZ** [comment]
Let's setup a Windows CI with github actions and see what the tests spit out. I believe we'll need to:

a) be careful about newlines and use platform-agnostic primitives instead of raw `\n`
b) make sure that UTF-8 characters are correctly output (we have some helper in cardano-wallet for this) 
c) pray.

**Comment by KtorZ** [comment]
I started toying around here: https://github.com/KtorZ/cardano-addresses/runs/854593414?check_suite_focus=true

And indeed, I can see that tests failing with some interesting logs similar to the above.

**Comment by rvl** [comment]
Yes you can't simply output utf-8 encoded text and hope that it will work.
It's possible to avoid the exception by forcing haskell to use utf-8 for its output handles.

But if the system encoding is not utf-8 then you will see mojibake.
On windows you can avoid that by changing the code page of the console.
On linux you can't do that, but most linux systems default to utf-8 anyway.

**Comment by KtorZ** [comment]
>  On windows you can avoid that by changing the code page of the console.

That's what I did yesterday indeed but it didn't quite help in CI at least (I believe Github Windows servers are configured to use utf-8 in the first place, but it might help in some other cases). 

There are three tests failing at the moment on Windows:

```
test\Command\Address\PointerSpec.hs:46:5: 
malformed pointer 💩 💩 💩
       "cannot parse value `cardano-address: <stderr>: hPutChar: invalid argument (invalid character)\n" does not contain "Usage"
```

```
test\Command\Address\PaymentSpec.hs:41:5: 
malformed network 💩
       "option --network-tag: cannot parse value `cardano-address: <stderr>: hPutChar: invalid argument (invalid character)\n" does not contain "Usage"
```

```
test\Command\Address\BootstrapSpec.hs:57:5: 
invalid network 💩
       "option --network-tag: cannot parse value `cardano-address: <stderr>: hPutChar: invalid argument (invalid character)\n" does not contain "Usage"
```

I guess the "pattern" is quite obvious.

**Comment by rhyslbw** [comment]
I can reproduce this in the Daedalus nix-shell on linux:

``` console
[nix-shell:~/code/iohk/daedalus]$ cardano-address --help
Usage: cardano-address COMMAND
  Command-line for address and key manipulation in Cardano.

Available options:
  -h,--help                Show this help text

Available commands:
  recovery-phrase          About recovery phrases
  key                      About public/private keys
  address                  About addresses

cardano-address: <stdout>: hPutChar: invalid argument (invalid character)
```
Also see https://github.com/input-output-hk/cardano-addresses/issues/40#issuecomment-656512433

**Comment by rvl** [comment]
@KtorZ  For the failing unit test, you probably need to set the text encoding in the test suite -- like this:
https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Main.hs

@rhyslbw Ah OK the nix-shell probably has `LANG=C`. It should be fixed with @KtorZ branch.

**Comment by KtorZ** [comment]
I think this can now be closed. `--help` is done several times when running the test suite which now pass on Windows.
