### ISSUE TITLE
FR: Please update to latest address and key version

### ISSUE THREAD

**Issue by gitmachtl** [input-output-hk/cardano-addresses#42]
FR: Can you please update the code to use the latest Bech32 Address Format and also to get out the Payment and Staking/Delegation keys in a format so we can convert it to the same format cardano-cli uses it. This would be needed to have the operator funds/pledge accessable via a normal wallet like daedalus too and not only via cardano-cli commands.

Thx!

**Comment by KtorZ** [comment]
> to use the latest Bech32 Address Format

What do you mean exactly by that?

>  also to get out the Payment and Staking/Delegation keys in a format 

What do you mean ? One can already get various sort of keys with the command-line, in various sort of encoding format.


There are currently no impediments that I am aware of that would prevent any cross-compatibility between cardano-cli and cardano-addresses.

**Comment by gitmachtl** [comment]
The key format from cardano-address directly is like:

**Comment by gitmachtl** [comment]
The Key-Format from cardano-address directly is like:

`xprv1hrmfun04xpm9wkkw762nvk6eztzfattralqn6e3572n03kshnfvpj4fuaeqn6q24t83yyhrg9zx4vf6l72rs0xfdwuf52699p8rzlcprk7rqx6led8y9prearf6nqaehff62n0hmx9qrptyqttxdp6nzsuhs6uhp`

When you do a Key-Inspect it looks like:
```
$ cat test.payment.prv | ../cardano-address key inspect
{
    "chain_code": "23b786036bf969c8508f3d1a753077374a74a9befb314030ac805accd0ea6287",
    "key_type": "private",
    "extended_key": "b8f69e4df53076575acef695365b5912c49ead63efc13d6634f2a6f8da179a5819553cee413d015559e2425c68288d56275ff28707992d77134568a509c62fe0"
}
$ cat test.payment.pub | ../cardano-address key inspect
{
    "chain_code": "23b786036bf969c8508f3d1a753077374a74a9befb314030ac805accd0ea6287",
    "key_type": "public",
    "extended_key": "8719319c9d5fd90e7e148bfff62f15d3122e41f485e829aee9efbb1ffe91467f"
}
```

So how do we get this into a cardano-cli readable skey/vkey format?

```
{
    "type": "SigningKeyShelley",
    "description": "Payment Signing Key",
    "cborHex": "5820c6aa6f9321d93410a7a3ab0ce3f04036442061265554f3d22ca67ad3c8ac780f"
}

{
    "type": "PaymentVerificationKeyShelley",
    "description": "Payment Verification Key",
    "cborHex": "5820b6a6cb750b07e74a7653503be8bdeaf54cb16c00de804937a638274e27f8d120"
}
```

Can you tell me a command to convert it to this cborHex?

**Comment by gitmachtl** [comment]
We need a solution, that pool owners/operator can fund there pledge with an account associated to a mnemonic, so this can also be used/monitored with daedalus. So the solution would be to get the payment and staking keys out of cardano-address with a given mnemonic.

**Comment by gitmachtl** [comment]
what will be the more likely outcome for mainnet launch, having cardano-addresses ready to generate cardano-cli keys, or cardano-cli ready to accept cardano-addresses keys?

**Comment by KtorZ** [comment]
> or cardano-cli ready to accept cardano-addresses keys?

**Comment by gitmachtl** [comment]
Would it be possible in any way to get out the payment.vkey in a cardano-cli compatible format?

**Comment by KtorZ** [comment]
Interoperability between cardano-cli and cardano-addresses has been addressed through the following CIPs:

- https://cips.cardano.org/cips/cip5
- https://cips.cardano.org/cips/cip16
