### ISSUE TITLE
Non-piped stdin hangs process  

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-addresses#45]
Following on from https://github.com/input-output-hk/cardano-addresses/issues/40

Just updated the [Daedalus code ](https://github.com/input-output-hk/daedalus/blob/feature/cardano-addresses-integration/source/main/ipc/introspect-address.js#L21-L40)to use a `spawn`ed process, although it just hangs. Reproducible via via the Daedalus nix-shell on linux and [available binary](https://github.com/input-output-hk/cardano-addresses/actions/runs/164971086) :

```console
[nix-shell:~/code/iohk/daedalus]$ cardano-address address inspect
37btjrVyb4KG5pZKzLb6SAKtkBeKC99E6shTz874jhgcEjPRrxafJG96hP5w7xW3xwjoWxPQNZyvQ8K4RG6awvCuUcjX5DCJQRA3C9Air5bkbSeBSj
^C

[nix-shell:~/code/iohk/daedalus]$ echo 37btjrVyb4KG5pZKzLb6SAKtkBeKC99E6shTz874jhgcEjPRrxafJG96hP5w7xW3xwjoWxPQNZyvQ8K4RG6awvCuUcjX5DCJQRA3C9Air5bkbSeBSj | cardano-address address inspect
{
    "stake_reference": "none",
    "address_style": "Byron",
    "address_root": "f3bc1b4dcd320af11686c03f144d2886e4b6719d34105d5d0d69dd5e",
    "derivation_path": "581cececdc43d62416a06a2e6ca422ea8d434cc488e6a0b0575703aa56d4",
    "network_tag": 459045235
}
``` 

Using https://github.com/input-output-hk/cardano-addresses/commit/dc729b0ba5ba112ee2bfe471c4df947ea7c76f28

**Comment by rvl** [comment]
You need to send an EOF. Type Ctrl-D instead of Ctrl-C. In nodejs, make sure to close the process handle so that the buffers are flushed.

Same thing will happen with any tool which reads stdin. For example
```
rodney@blue:~ % xxd                                                               
hello
^C
rodney@blue:~ % printf hello | xxd                                                
00000000: 6865 6c6c 6f                             hello
rodney@blue:~ %                                                      
```

**Comment by rhyslbw** [comment]
Thanks @rvl
