### ISSUE TITLE
Can't inspect stake_test... addresses

### ISSUE THREAD

**Issue by adascanBovich** [input-output-hk/cardano-addresses#46]
Staking address created using commands:

`cardano-cli shelley stake-address key-gen --verification-key-file staking.vkey --signing-key-file staking.skey`

`cardano-cli shelley stake-address build --staking-verification-key-file staking.vkey > staking.addr`

`shelley@localhost:~/keys/keys1$ cat staking.addr`

`stake_test1uqr6kpjry04lu9v2qu989r4vtdks202e8fz70z8mgzj96ugtnm6ld`

Now trying to use _inspect_ command for it:

<img width="731" alt="Screenshot 2020-07-15 at 8 08 30" src="https://user-images.githubusercontent.com/58727428/87505790-6e75b280-c672-11ea-8f8a-216275f68693.png">

Make sure that _inspect_ command is working for addr_test.. address:

<img width="731" alt="Screenshot 2020-07-15 at 8 08 47" src="https://user-images.githubusercontent.com/58727428/87505871-a2e96e80-c672-11ea-91a7-929574ee7e75.png">

**Comment by hasufell** [comment]
## QA

Changeset: https://github.com/input-output-hk/cardano-addresses/commit/9a22296d40fe7df30e9258ce151076e792b15d12

The primary change that meets the acceptance criteria is:

https://github.com/input-output-hk/cardano-addresses/blob/9a22296d40fe7df30e9258ce151076e792b15d12/core/lib/Cardano/Address/Style/Shelley.hs#L511-L526

This corresponds to the ledger spec:

https://github.com/input-output-hk/cardano-ledger-specs/blob/736c9295f5896de28fbcedc6a8fc4d509fb78d10/shelley/chain-and-ledger/shelley-spec-ledger-test/cddl-files/shelley.cddl#L98-L99

The tests are at:

https://github.com/input-output-hk/cardano-addresses/blob/9a22296d40fe7df30e9258ce151076e792b15d12/command-line/test/Command/Address/InspectSpec.hs#L42-L48

These tests/hashes must fail with an older version of `cardano-addresses` (without the code above).

**Comment by piotr-iohk** [comment]
lgtm. I thought it might be good to add additional tests -> https://github.com/input-output-hk/cardano-addresses/pull/61
