### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-addresses#47]
@rvl asked me to raise this. @rhyslbw pointed me to this project but I ended up using `cardano-api` from `cadano-node` instead because I was already using deps from that repo.

However when I looked at this I noticed what I consider to be (minor) problems of insufficient granularity. This repo is currently a single cabal project with a library and an executable. What I thought odd was that the library depends on `ansi-terminal` and `optparse-applicative`.

As a potential user I think this project should be two distinct cabal projects:

* cardano-addresses - A library, that is probably mostly pure functions (with the exception of key generation etc) that are reusable. In particualr this would not depend on `ansi-terminal` or `optparse-applicative`. This would be used by people who need to operate on addresses but do not need things like the CLI parsers.
* cardano-addresses-cli - A library containing the rest of the IO stuff and the CLI parsers and the executable.

This is definitely not high priority. Just an observation that @rvl thought was worth documenting.

**Comment by rvl** [comment]
Thanks for documenting @erikd.

**Comment by KtorZ** [comment]
Indeed. Sounds like a reasonable thing to do.

**Comment by KtorZ** [comment]
@erikd let me know if this helps --> https://github.com/input-output-hk/cardano-addresses/pull/49
