### ISSUE TITLE
Increase default length of mnemonic phrase.

### ISSUE THREAD

**Issue by jonathanknowles** [input-output-hk/cardano-addresses#52]
# Context

Version 2.0.0 of Daedalus generates wallets with recovery phrases that are 24 words in length.

# Decision

Change the default mnemonic phrase length from 15 words to 24 words in the `cardano-addresses` CLI library (as used by `cardano-wallet`):

https://github.com/input-output-hk/cardano-addresses/blob/d4d178cb12fca3e9fcb23302325828e159600f0a/command-line/lib/Options/Applicative/MnemonicSize.hs#L73

# Acceptance Criteria

- [ ] When invoked without a specific number of words, the `cardano-addresses` CLI library (as used by `cardano-wallet`) should generate a mnemonic phrase of 24 words in length by default.

# Development 

# QA

**Comment by piotr-iohk** [comment]
Perhaps we could add some test for that. I suppose there isn't any.

I see that on cardano-wallet... cardano-wallet recover-phrase generate still spits 15 words. Should cardano-addresses be bumped in cardano-wallet to include this?

I notice now also (not related to this change) but the coverage on cardano-addresses dropped to 41%... I think it was much higher... something happened? :thinking: @jonathanknowles, @KtorZ ?

**Comment by KtorZ** [comment]
> @piotr-iohk I notice now also (not related to this change) but the coverage on cardano-addresses dropped to 41%... 

Yes, the coverage calculation broke after we re-organized the repository into multiple packages. I had to rework a bit the script for calculating the coverage but I forgot to push the new version somehow :shrug: ... I also noticed yesterday and pushed the updated version that supports multi-package repositories. Coverage is back to normal :)
