### ISSUE TITLE
'cardano-address address payment --network-tag 0' command can't make testnet address

### ISSUE THREAD

**Issue by sjlee1125** [input-output-hk/cardano-addresses#55]
Shelley testnet address's prefix is addr_test
But cardano-address payment --network-tag 0 Command generate just addr prefix address
How can i generate shelley testnet address?

**Comment by KtorZ** [comment]
Note that the prefix is just a presentation concern what matters is the encoded data. Although we will update that soon to return a `addr_test` prefix, there's nothing intrinsically wrong with the generated address.

Should you really need an `addr_test` prefix, have a look at [bech32](https://github.com/input-output-hk/bech32):

```
$ bech32 addr_test <<< addr1....
addr_test1....
```

**Comment by hasufell** [comment]
## QA

Commit: https://github.com/input-output-hk/cardano-addresses/commit/07fb6efb752691bde85c8e80fceb0e92479fcff6

We use [bech32With](https://github.com/input-output-hk/cardano-addresses/blob/master/core/lib/Cardano/Address.hs#L111) to generate the human readable prefix depending on the network tag: https://github.com/input-output-hk/cardano-addresses/blob/07fb6efb752691bde85c8e80fceb0e92479fcff6/command-line/lib/Command/Address/Payment.hs#L76-L79

This is tested in https://github.com/input-output-hk/cardano-addresses/blob/07fb6efb752691bde85c8e80fceb0e92479fcff6/command-line/test/Command/Address/PaymentSpec.hs#L16-L17

**Comment by piotr-iohk** [comment]
I have added https://github.com/input-output-hk/cardano-addresses/pull/60 to update examples to reflect this change.

With this change we seem to have a bit incoherent situation now. We have `payment` and `stake` address that are generated with `addr_test` or `stake_test` prefix when using `network-tag 0`, but pointer and delegation addresses are still using `addr` prefix:

**pointer**
```
cardano-address recovery-phrase generate --size 15 \
    | cardano-address key from-recovery-phrase Shelley > root.prv
  
cat root.prv \
    | cardano-address key child 1852H/1815H/0H/0/0 > addr.prv
  
cat addr.prv \
    | cardano-address key public \
    | cardano-address address payment --network-tag 0\
    | cardano-address address pointer 42 14 0
  addr1grq8e0smk44luyl897e24gn6qfkx4ax734r6pzq29zcew032pcqqef7zzu
```

**delegation**

```
cardano-address recovery-phrase generate --size 15 \
    | cardano-address key from-recovery-phrase Shelley > root.prv
  
cat root.prv \
    | cardano-address key child 1852H/1815H/0H/2/0 > stake.prv
  
cat root.prv \
    | cardano-address key child 1852H/1815H/0H/0/0 > addr.prv
  
cat addr.prv \
    | cardano-address key public \
    | cardano-address address payment --network-tag 0 \
    | cardano-address address delegation $(cat stake.prv | cardano-address key public)
  addr1qpj2d4dqzds5p3mmlu95v9pex2d72cdvyjh2u3dtj4yqesv27k...
```


Perhaps they should be also updated?

**Comment by piotr-iohk** [comment]
Closing this one, addressed the issue in https://github.com/input-output-hk/cardano-addresses/issues/62.
