### ISSUE TITLE
Pointer and delegation addresses with --network-tag 0 do not generate address with prefix addr_test

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/cardano-addresses#62]
# Context

With change related to https://github.com/input-output-hk/cardano-addresses/issues/55 we seem to have a bit incoherent situation now. We have `payment` and `stake` address that are generated with `addr_test` or `stake_test` prefix when using `network-tag 0`, but pointer and delegation addresses are still using `addr` prefix:

**pointer**
```
cardano-address recovery-phrase generate --size 15 \
    | cardano-address key from-recovery-phrase Shelley > root.prv
  
cat root.prv \
    | cardano-address key child 1852H/1815H/0H/0/0 > addr.prv
  
cat addr.prv \
    | cardano-address key public \
    | cardano-address address payment --network-tag 0\
    | cardano-address address pointer 42 14 0
  addr1grq8e0smk44luyl897e24gn6qfkx4ax734r6pzq29zcew032pcqqef7zzu
```

**delegation**

```
cardano-address recovery-phrase generate --size 15 \
    | cardano-address key from-recovery-phrase Shelley > root.prv
  
cat root.prv \
    | cardano-address key child 1852H/1815H/0H/2/0 > stake.prv
  
cat root.prv \
    | cardano-address key child 1852H/1815H/0H/0/0 > addr.prv
  
cat addr.prv \
    | cardano-address key public \
    | cardano-address address payment --network-tag 0 \
    | cardano-address address delegation $(cat stake.prv | cardano-address key public)
  addr1qpj2d4dqzds5p3mmlu95v9pex2d72cdvyjh2u3dtj4yqesv27k...
```

Perhaps they should be also updated? 

# Decision

# Acceptance Criteria

---

# Development 

# QA

**Comment by KtorZ** [comment]
QA: 

- Added new test scenarios in for the `pointer` and `delegation` commands showing that the prefix is correctly set to `addr_test` if the base address is a testnet address:

  https://github.com/input-output-hk/cardano-addresses/blob/af81451427294b5e8d328a80f725de81c94bb0bb/command-line/test/Command/Address/PointerSpec.hs#L16-L26

  https://github.com/input-output-hk/cardano-addresses/blob/af81451427294b5e8d328a80f725de81c94bb0bb/command-line/test/Command/Address/DelegationSpec.hs#L16-L24

**Comment by piotr-iohk** [comment]
LGTM.
