### ISSUE TITLE
Need help.

### ISSUE THREAD

**Issue by Fell-x27** [input-output-hk/cardano-addresses#63]
Hi! I'm trying to reimplement some derivation mechanics for myself to get more deep understanding of the keys-management.
There are 3 options for root.prv calculation: Byron, Icarus and Shelley. 
Icarus and Shelley return the same result. 
And I can reach the same result by:
var mnemonic = 'hill safe victory sun tired fetch police radio sport output buyer deny april fringe stumble';
//var mnemonic = 'ghost buddy neutral broccoli face rack relief odor swallow real once ecology';
var entropy = bip39.mnemonicToEntropy(mnemonic);

1. convert mnemonic to entropy
2. simple derive private key from this entropy with Bip32 and empty password.

So, I'll get the same result as cardano-addresses provides with the same mnemonic. It's very clear to me.

But what's wrong with the Byron option? The steps described above are not working properly. Isn't it Bip32 key? Or there should be some hardcoded password? Or Smth else?

**Comment by Fell-x27** [comment]
And what does "--legacy" derivation mean? What is low-level difference?

**Comment by rvl** [comment]
Hi @Fell-x27 - apologies for the late reply.

These are the key derivation functions used by cardano-addresses:
1. https://github.com/input-output-hk/cardano-addresses/blob/39baf7407ceb7acef78e5ed3b0043da2d772f6b8/core/lib/Cardano/Address/Derivation.hs#L246-L269
2. https://github.com/input-output-hk/cardano-crypto/blob/2547ad1e80aeabca2899951601079408becbc92c/src/Cardano/Crypto/Wallet.hs#L91-L133

The key derivation function is different for byron (`generate`) and icarus/shelley (`generateNew`) wallets.

**Comment by KtorZ** [comment]
Closing this old ticket, feel free to re-open if necessary and still relevant :+1:
