### ISSUE TITLE
cardano-address version doesn't show revision (bin from cardano-wallet bundle only)

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/cardano-addresses#70]
# Context

cardano-address from https://hydra.iohk.io/job/Cardano/cardano-wallet/cardano-wallet-win64
```
c:\Users\piotr\Downloads>cardano-address version
2.0.0 @ unknown revision
```

The one from release shows revision ok:
```
c:\Users\piotr\Downloads\cardano-addresses-2.0.0-windows64>cardano-address version
2.0.0 @ 9a64226fd749513ad0ed2e43e663f7132c92faa7
```
The same goes for Linux:

```
./cardano-address version
2.0.0 @ unknown revision
```
# Decision

# Acceptance Criteria

Both should show revision.

---

# Development 

# QA

**Comment by rvl** [comment]
This should be fixed now.
