### ISSUE TITLE
Key derivation used in script addresses according to coming CIP

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-addresses#72]
# Context

We consider the following derivation paths (cf. BIP-32) for a multi-signature wallet address:

m / purpose' / coin_type' / account_ix' / role / address_ix

To associate multi-signature keys to a wallet, we reserve role=3 as an extension of CIP-1852. Wallet softwares should prevent the creation of new multisig keys before a key is used in an on-chain script.

Allowed values of the role level are summarized in the table below:

value | description
-- | --
role = 0 | Identifies public payment keys
role = 1 | Identifies internal payment keys (change)
role = 2 | Identifies stake keys
role = 3 | Identifies multi-signature keys

Example of derivation path:

m/1852’/1815’/0’/3/0

Rationale

    Multisig keys are scoped to accounts, which allows wallet’s owners to separate their activity easily.

    One or many keys can be created from an account public key via soft-derivation.

This allows participant to easily share their multisig keys to participate in a multisig script without having to fetch for their hardware device. The device is still required for signing.

# Decision

We are providing the implementation in line with the above.

# Acceptance Criteria

1. We can derive keys according to the above scheme
2. Tests are added 

---

# Development 

# QA

**Comment by piotr-iohk** [comment]
lgtm.
