### ISSUE TITLE
Multisig script construction

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-addresses#73]
# Context

We want to be able to construct script needed for multisig address.

# Decision

Support for multisig construction is to be delivered. We should be able to construct nested predicates. (verification keys with all/any/atLeast guard). Introduce CLI enabling constructing hash from key, and constructing script hash 

# Acceptance Criteria
1. Multisig script type is defined and needed instances delivered
2. Multisig script can be constructed via CLI
3. Multisig script construction is tested 
4. Hash of key functionality in CLI is added

---

# Development 

# QA 

There were a number of test suites added. The user now can do the following:

How to construct a script and calculate its hash in cardano-addresses

1.  Let's say I have the following recovery phrase
```
$ cat recovery-phrase.txt
nothing heart matrix fly sleep slogan tomato pulse what roof rail since plastic false enlist
```

2. Now we create root key
```
$ cat recovery-phrase.txt | cardano-address key from-recovery-phrase Shelley > root.xprv
xprv1apjwjs3ksgm5mnnk0cc5v5emgv0hmafmmy8tffay5s2ffk69830whwznr46672ruucdzwwtv9upv72e4ylrypyz5m6cyh0p00t7n3u3agt20lv32j4kxcqlkzu78nzjx0ysxxlc2ghfz9prxfmrds802xsh67k7t
```

3. And derive two signing keys according to multisig CIP (TO-DO add link when available)
```
$ cat root.xprv | cardano-address key child 1852H/1815H/0H/3/0 > signingKey1.xprv
xprv1nrywvqyuwefulu6mqmpxelz92kcy0zluu5kf5p74c6l6f6z9830pfvcvgen923akys2d2fmlh8t3fttj6nvx040k30ek8k62jyvv9p38c8lyuz9qkyhgnyme7ay742e7nemd037jdevpl688fdvtcfq9eqpnkr57
$ cat root.xprv | cardano-address key child 1852H/1815H/0H/3/1 > signingKey2.xprv
xprv1vpr59y3p3cfggk85x6dvmlpkwm9f4c99lvkmw8r6j5vwd669830rw5lvsuh8530q897ht9a297kw2qhkpvn7kk98njhdg3scter64uukrwtashzde54v8ery8a92npx4e22ffg45mtshe6ewpnzjx2cn9qs42k0f
```

4. The corresponding verification keys and their hashes can be obtained as follows
```
$ cat signingKey1.xprv | cardano-address key public | cardano-address key hash --base16 > verKey1.hash
de5861cd05e99985b2c586ab383790c6600990809206f84e96eadaea
$ cat signingKey2.xprv | cardano-address key public | cardano-address key hash --base16 > verKey2.hash
aca52d7d28ce353f4766e4e2c8cc2208c7113d794e776eafb8c07a80
```

5. Notice the default hrp (in bech32) for the hash of verification key - **xpub_hash**
```
$ cat signingKey1.xprv | cardano-address key public | cardano-address key hash 
xpub_hash1mevxrng9axvctvk9s64nsduscesqnyyqjgr0sn5katdw5egajw2
```

6. Now we can construct the script using the hashes of verification keys
```
$ echo "all [$(cat verKey1.hash),$(cat verKey2.hash)]" > script.txt
all [de5861cd05e99985b2c586ab383790c6600990809206f84e96eadaea,aca52d7d28ce353f4766e4e2c8cc2208c7113d794e776eafb8c07a80]
```

7. Having a script constructed we can get its script hash that could go to payment or staking credential when creating the address. Please notice the default hrp (in bech32) - **script_hash**
```
$ cardano-address script hash “$(cat script.txt)”
script_hash15hx806zf0g8kcv399dpxf6fq4l98myqpvvzj2rltg465uz36435
```

```

**Comment by piotr-iohk** [comment]
LGTM.
