### ISSUE TITLE
Script address construction

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-addresses#74]
# Context

When having a capability to construct verification keys and script we want to have a way to construct multisig-script address for a given network tag

# Decision

We add a way to construct multisig address for a given script and network tag properly formatted.
# Acceptance Criteria

1. Address with script as stake or payment credential can be constructed
2. Better script error reporting
3. Use **script_hash** hrp in bech32 for script hash used in either payment/stake credential

---

# Development 

# QA 

See tests added, also CLI support added with tests. would be worth to play with it. The number of comments with code snippets also were updated.

**Comment by piotr-iohk** [comment]
LGTM.

> See tests added, also CLI support added with tests. would be worth to play with it.

I played, it was worth it. :)
